### PR TITLE
Security: Throw error if URI contains illegal characters

### PR DESCRIPTION
**Pull request by NSTikhomirov**

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
Ok. And one question - does it process zero bytes correctly?

**Comment by NSTikhomirov** [comment]
> Ok. And one question - does it process zero bytes correctly?

```
using namespace std::string_literals;
std::string uri("test\0test"s);
uri.erase(std::remove_if(uri.begin(), uri.end(), ::isspace), uri.end());
std::cout << uri << "\n";
```
will return `test`
hex(uri) => `74657374` => `test`

**Comment by alexey-milovidov** [comment]
Because this code is incorrect: `std::string uri("test\0test");`

**Comment by NSTikhomirov** [comment]
> Because this code is incorrect: `std::string uri("test\0test");`

That's true, did not think about it: |
```
#include <algorithm>
#include <iostream>
#include <string>

std::string string_to_hex(const std::string& input)
{
    static const char* const lut = "0123456789ABCDEF";
    size_t len = input.length();

    std::string output;
    output.reserve(2 * len);
    for (size_t i = 0; i < len; ++i)
    {
        const unsigned char c = input[i];
        output.push_back(lut[c >> 4]);
        output.push_back(lut[c & 15]);
    }
    return output;
}

int main()
{
    using namespace std::string_literals;
    std::string uri("test\0test"s);
    uri.erase(std::remove_if(uri.begin(), uri.end(), ::isspace), uri.end());
    std::cout << uri << " (" << string_to_hex(uri) << ")" << "\n";
}
```
Result: `testtest (746573740074657374)`

I think the best solution to this problem is
```
uri.erase(std::remove_if(uri.begin(), uri.end(), [](int ch) {
    return !std::isprint(ch) or ch == ' ';
}), uri.end());
```

**Comment by alexey-milovidov** [comment]
But now it depends on locale.

**Comment by alexey-milovidov** [comment]
And why we should silently drop these characters? Better to throw an exception.

**Comment by NSTikhomirov** [comment]
Made a throw when finding control characters or spaces

**Comment by alexey-milovidov** [comment]
Ok. Changed to also filter non-ASCII.
Now it's good enough. (But it doesn't correspond to RFC one to one).

**Comment by alexey-milovidov** [comment]
https://github.com/yandex/ClickHouse/pull/6466

**Pull request merged**
