### PR TITLE
Fix empty files creation when rotating on full disk

### PR DESCRIPTION
**Pull request by zvonand**
Fix for https://github.com/ClickHouse/ClickHouse/issues/37766

### CODE REVIEW

**Comment by Enmk** [comment]
Please see https://github.com/ClickHouse/ClickHouse/issues/37766#issuecomment-1262206568 for details

**Comment by zvonand** [comment]
@evillique any updates on this?

**Comment by zvonand** [comment]
Any updates from @evillique ?

**Review by evillique — APPROVED** [review]

**Comment by evillique** [comment]
With this fix, Poco completely stops the rotation of logs if the disk space is not enough even for 1 .log file, so we would only have logs from the start of the server. In a similar environment without this, there will only be files with size 0, so having at least some logs is probably better than nothing.

Having said that, when the space is enough for at least 1 .log and 1 compressed .log.gz file it will still continue to create empty compressed files:
```
/var/log/clickhouse-server# ll
total 44
drwxrwx--- 3 clickhouse clickhouse   280 Nov  2 22:56 ./
drwxr-xr-x 1 root       root        4096 Nov  2 22:54 ../
-rw-r----- 1 clickhouse root        4799 Nov  2 22:54 clickhouse-server.err.log
-rw-r----- 1 clickhouse root           0 Nov  2 22:56 clickhouse-server.log
-rw-r----- 1 clickhouse root           0 Nov  2 22:56 clickhouse-server.log.0.gz
-rw-r----- 1 clickhouse root           0 Nov  2 22:56 clickhouse-server.log.1.gz
-rw-r----- 1 clickhouse root           0 Nov  2 22:56 clickhouse-server.log.2.gz
-rw-r----- 1 clickhouse root           0 Nov  2 22:55 clickhouse-server.log.3.gz
-rw-r----- 1 clickhouse root           0 Nov  2 22:55 clickhouse-server.log.4.gz
-rw-r----- 1 clickhouse root        1321 Nov  2 22:55 clickhouse-server.log.5.gz
-rw-r----- 1 clickhouse root        2020 Nov  2 22:55 clickhouse-server.log.6.gz
drwxr-x--- 2 root       root          60 Nov  2 22:56 preprocessed_configs/
-rw------- 1 clickhouse root       20480 Nov  2 22:57 stderr.log
-rw-r----- 1 clickhouse root           0 Nov  2 22:54 stdout.log
```

So in general it does not change much but also does not seem to break anything, so probably ok to have.

**Pull request merged**
